//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalFilingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageIndex()
        {
            this.ImageIndex1 = new HashSet<ImageIndex>();
            this.Images = new HashSet<Image>();
        }
    
        public System.Guid Id { get; set; }
        public string DivisonCode { get; set; }
        public string DepartmentCode { get; set; }
        public string GOCode { get; set; }
        public string DeskCode { get; set; }
        public string SubjectCode { get; set; }
        public string FileCode { get; set; }
        public string FileOpenYear { get; set; }
        public string LetterNo { get; set; }
        public string MinuteYear { get; set; }
        public string MeetingMinute { get; set; }
        public Nullable<bool> IsMeetingMinute { get; set; }
        public string InformattedLetterNo { get; set; }
        public string Keyword { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageIndex> ImageIndex1 { get; set; }
        public virtual ImageIndex ImageIndex2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
